name: TntNoExplode
version: ${project.version}
main: esp.lbelmar.tntnoexplode.TntNoExplode
api-version: 1.17
authors: [ LuisBelloch ]
description: Configure the explosions behaviour

commands:
  configExplosion:
    description: Configure the explosions behaviour
    usage: /configExplosion
    permission: minecraft.command.gamerule
